// KEYS.H : 키보드 입력키들에 대한 매크로 정의.

#ifndef __KEYS_H
#define __KEYS_H

#define FALSE           0
#define TRUE            !FALSE

#define OFF             0
#define ON              !OFF

#define PLUS            61
#define MINUS           45
#define ENTER           13
#define ESC             27
#define TAB             9
#define SPACE           32
#define BSPACE          8
#define F1              315
#define F2              316
#define F3              317
#define F4              318
#define F5              319
#define F6              320
#define F7              321
#define F8              322
#define F9              323
#define F10             324
#define HOME            327
#define END             335
#define UP              328
#define DOWN            336
#define RIGHT           333
#define LEFT            331
#define INS             338
#define DEL             339
#define PGUP            329
#define PGDN            337
#define ALT_A           286
#define ALT_B           304
#define ALT_C           302
#define ALT_D           288
#define ALT_E           274
#define ALT_F           289
#define ALT_G           290
#define ALT_H           291
#define ALT_I           279
#define ALT_J           292
#define ALT_K           293
#define ALT_L           294
#define ALT_M           306
#define ALT_N           305
#define ALT_O           280
#define ALT_P           281
#define ALT_Q           272
#define ALT_R           275
#define ALT_S           287
#define ALT_T           276
#define ALT_U           278
#define ALT_V           303
#define ALT_W           273
#define ALT_X           301
#define ALT_Y           277
#define ALT_Z           300

#define CTRL_A          1
#define CTRL_B          2
#define CTRL_C          3
#define CTRL_D          4
#define CTRL_E          5
#define CTRL_F          6
#define CTRL_G          7
#define CTRL_H          8
#define CTRL_I          9
#define CTRL_J          10
#define CTRL_K          11
#define CTRL_L          12
#define CTRL_M          13
#define CTRL_N          14
#define CTRL_O          15
#define CTRL_P          16
#define CTRL_Q          17
#define CTRL_R          18
#define CTRL_S          19
#define CTRL_T          20
#define CTRL_U          21
#define CTRL_V          22
#define CTRL_W          23
#define CTRL_X          24
#define CTRL_Y          25
#define CTRL_Z          26

#endif
