
SC_INDEX                equ     03c4h   ;Sequence Controller Index
CRTC_INDEX              equ     03d4h   ;CRT Controller Index
MISC_OUTPUT             equ     03c2h   ;Miscellaneous Output register
GRP_INDEX               equ     03ceh   ;Graphic Controller Index
SCREEN_OFF              equ     0a0000h ;32 bit offset of display memory
MAP_MASK                equ     02h     ;Map Mask register index in SC
START_ADDRESS_HIGH      equ     0ch     ;start address high db
START_ADDRESS_LOW       equ     0dh     ;start address low db

